version: '3.3'
services:
  app:
    image: node:lts-alpine
    working_dir: /client
    volumes:
      - ./client:/client
    ports:
      - 8080:8080
    command: >
      sh -c "npx quasar dev"
    # npm install -g @quasar/cli && npm install &&
  server:
    image: node:lts-alpine
    working_dir: /server
    volumes:
      - ./server:/server:rw
    ports:
      - 3030:3030
    links:
      - mongo
    # NODE_ENV variable is used by feathersjs to determine which config
    # file to merge with the default.json file. Update as needed.
    environment:
      NODE_ENV: docker
    command: >
      sh -c "npm install mongodb && npm install && npm run docker"

  mongo:
    image: mongo:latest
    expose:
      - "27019"
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vevedh
      MONGO_INITDB_ROOT_PASSWORD: eclipses
      #MONGO_DATA_DIR: /data/db     
    volumes:
      - ./mongo/data:/data/db
      
#volumes:
#  mongodb_container: